Expand tabs.

diff --git a/ncp b/ncp
--- a/ncp
+++ b/ncp
@@ -18,8 +18,8 @@ EOM
 }
 
 if ! which tmux > /dev/null; then
-	echo>&2 "$(basename "$0"): tmux: command not found"
-	exit 3
+    echo>&2 "$(basename "$0"): tmux: command not found"
+    exit 3
 fi
 
 dest_hostname=
